# Hand-authored purpose descriptions for each of the 115 PE binaries in the TSS
# archive, cross-checked against tool_inventory.json (grep evidence from all 695
# bundled .ps1/.psm1 scripts). Where a script match was a false positive (common
# short substrings like "du", "kd", "SAN", "handle" colliding with unrelated code/
# comments), that is flagged explicitly rather than treated as instrumentation
# evidence. Purpose text for well-known public Microsoft/Sysinternals/WDK tools
# draws on their established public documentation; for TSS-internal/custom tools,
# purpose is derived only from the script context found.

PURPOSES = {
    "BIN/AgentConfigManagerLib.dll": "Support library, no direct script reference found; name and bundling alongside MDEClientAnalyzer.exe suggest it is a dependency of the Microsoft Defender for Endpoint client analyzer, not independently confirmed.",
    "BIN/ConnectivityDiagnosis.exe": "Network/telemetry connectivity diagnostic tool invoked by the UEX_Telemetry trace scenario with -verbose, output captured to a _Telemetry_ConnectivityDiagnosis.txt file.",
    "BIN/Coreinfo.exe": "Sysinternals Coreinfo — dumps CPU topology, cache, and supported instruction-set features. TSS checks for its presence via Get-Command before use.",
    "BIN/DatabaseAnalyzer.exe": "Active Directory database (ESE/NTDS.dit) analyzer tool, migrated into the ADS (Active Directory Services) module per its changelog.",
    "BIN/DisplayExtendedAttribute.exe": "Displays Windows Information Protection / DLP extended file attributes; referenced by the DLP diagnostics script as a manually-invoked companion tool.",
    "BIN/MDEClientAnalyzer.exe": "Microsoft Defender for Endpoint (MDE) Client Analyzer — official Microsoft tool for diagnosing MDE sensor onboarding/health issues; downloaded and invoked by the DefTools MDE performance analyzer script.",
    "BIN/MDEClientAnalyzerPreviousVersion.exe": "No direct script reference found; by naming convention, a fallback/compatibility copy of MDEClientAnalyzer.exe for environments requiring an older analyzer version.",
    "BIN/Procmon.exe": "Sysinternals Process Monitor — real-time file system/registry/process/thread activity monitor; started and stopped via Start-Process with dynamically built argument lists (see prior conversation turn for exact invocation lines).",
    "BIN/SQLCheck.exe": "SQL Server connectivity/health check tool, gated behind the NET_SQLcheck switch and also invoked from the psSDP SQL base diagnostics script.",
    "BIN/Showpriv.exe": "Displays the effective Windows privileges held by the current token (e.g. SeTakeOwnershipPrivilege); invoked by the psSDP user-rights diagnostic script.",
    "BIN/Sysmon.exe": "Sysinternals System Monitor — kernel-driver-based ETW logger for detailed process creation, network connection, and file-change events; one of the trace types named in TSS's own synopsis.",
    "BIN/VmlTrace.exe": "Hyper-V VML (virtualization infrastructure driver) trace collection tool, used for Hyper-V verbosity tracing per the storage (SHA) module and a dedicated VMLverbosity helper script.",
    "BIN/VmlTrace_2012.exe": "Windows Server 2012 (build 9200) -specific build of VmlTrace.exe, selected conditionally based on detected OS build.",
    "BIN/WinHTTPDiag.exe": "WinHTTP configuration/proxy diagnostic tool, invoked with -i to dump WinHTTP settings as part of the NET_Proxy network trace scenario.",
    "BIN/accesschk.exe": "Sysinternals AccessChk — reports effective permissions on files, registry keys, and services; invoked as part of DHCP-related access-check data collection in the NET module.",
    "BIN/autorunsc.exe": "Sysinternals Autoruns (command-line edition) — lists autostart execution points; invoked by a psSDP registry-autoruns diagnostic script.",
    "BIN/avdnettest.exe": "Azure Virtual Desktop network connectivity test tool, located and invoked by the MSRD-Collect (Multi-Session Remote Desktop) module for AVD network diagnostics.",
    "BIN/devcon.exe": "Microsoft Device Console (from the WDK) — enumerates and manages devices/drivers; invoked by a psSDP setup diagnostics script.",
    "BIN/diskspd.exe": "Microsoft DiskSpd — storage I/O performance benchmarking tool; used to generate synthetic load for SMB performance test scenarios.",
    "BIN/fruti_1903.exe": "Internal storage/filter-driver diagnostic tool ('Fruti') used for storage tracing in the SHA (storage) module; this build selected for OS build >= 18362 (1903+).",
    "BIN/fruti_RS1.exe": "Same Fruti storage diagnostic tool as fruti_1903.exe; this build selected for older OS builds (< 18362 / pre-1903, i.e. RS1-era).",
    "BIN/handle.exe": "Likely Sysinternals Handle (lists open handles per process) by name and bundling convention, but the automated script match was a false positive (matched the unrelated phrase 'handle ownership issues' in a GUI code comment) — no confirmed direct invocation found in the reviewed scripts.",
    "BIN/kd.exe": "Likely the Microsoft Kernel Debugger (kd.exe, from Debugging Tools for Windows) by name and bundling alongside cdb.exe/livekd.exe, but the automated script match was a false positive (matched inside an unrelated base64-encoded certificate blob) — no confirmed direct invocation found.",
    "BIN/livekd.exe": "Sysinternals LiveKD — allows running the kernel debugger against a live system; gated behind an explicit -LiveKD parameter/switch in TSS.ps1.",
    "BIN/npivtool.exe": "Storage/Fibre Channel NPIV (N-Port ID Virtualization) diagnostic tool, invoked with -listallports and -showlunmappings in the storage (SHA) module.",
    "BIN/nvspinfo.exe": "Referenced by name in a Hyper-V networking diagnostic script, but that script actually invokes companion .js files (nvspinfo.js/nvspinfov2.js) via cscript rather than this .exe directly — its exact role alongside those scripts was not confirmed.",
    "BIN/perfctrl.dll": "No direct script reference found; name suggests a performance-counter control helper library, plausibly used alongside PerfMon-based data collection, not independently confirmed.",
    "BIN/poolmon.exe": "Windows kernel pool memory usage monitor (from the WDK); gated behind a -PoolMon parameter and -noPoolMon switch (run automatically at trace start/stop unless disabled).",
    "BIN/procdump.exe": "Sysinternals ProcDump — captures process memory dumps on demand or on a trigger (e.g. crash, hang, CPU threshold); gated behind -ProcDump and -ProcDumpAppCrash parameters.",
    "BIN/psping.exe": "Sysinternals PsPing — TCP/ICMP latency and bandwidth testing tool; referenced as a suggested manual tool in one script and re-implemented as an inline TCP probe elsewhere, rather than directly invoked as a subprocess in the paths reviewed.",
    "BIN/rpccfg.exe": "Classic Microsoft RPC configuration tool — invoked with /l to dump RPC endpoint configuration as part of RPC diagnostic data collection in the NET module.",
    "BIN/rpcdump.exe": "Classic Microsoft RPC endpoint-mapper enumeration tool — invoked with /v /i to dump registered RPC interfaces/endpoints, alongside rpccfg.exe in the same NET module diagnostic pass.",
    "BIN/windowsperformancerecordercontrol.dll": "No direct script reference found; name indicates a Windows Performance Recorder (WPR) control-library component, plausibly a dependency of wpr.exe/xperf.exe tracing, not independently confirmed.",
    "BIN/wpr.exe": "Windows Performance Recorder — ETW-based system tracing tool; orchestrated via TSS's WPR profile listing/selection logic (-ListSupportedWPRScenario, WPRprofiles parameter type) and the -WPR trace-start pathway noted earlier in this review.",
    "BIN/xperf.exe": "Windows Performance Toolkit's xperf — ETW-based system tracing and analysis tool; orchestrated via a parallel Xperf profile listing/selection logic (-ListSupportedXperfProfile) alongside wpr.exe.",
    "BINARM/NTttcp.exe": "Microsoft NTttcp — network throughput benchmarking tool; ARM64 build of the same tool used for network performance tests (see BINx64/BINx86 entries for command construction).",
    "BINARM/ProcDump.exe": "ARM64 build of Sysinternals ProcDump (see BIN/procdump.exe).",
    "BINARM/Procmon.exe": "ARM64 build of Sysinternals Process Monitor (see BIN/Procmon.exe).",
    "BINARM/Sysmon64a.exe": "ARM64 build of Sysinternals Sysmon (see BIN/Sysmon.exe); no direct script reference found beyond architecture-specific bundling, consistent with the other ARM64 tool builds.",
    "BINARM/notmyfaultc.exe": "ARM64 build of Sysinternals NotMyFault (see BINx64/notmyfaultc.exe).",
    "BINx64/Checksym.exe": "Microsoft support tool that enumerates file versions across the local machine; invoked by a dedicated tss_ChkSym.ps1 helper script.",
    "BINx64/NTttcp.exe": "Microsoft NTttcp — network throughput benchmarking tool; invoked with constructed single-thread/multi-thread command lines as part of performance (PRF) network test scenarios.",
    "BINx64/PsGetsid.exe": "Sysinternals PsGetSid — resolves/converts Windows SIDs; invoked with /AcceptEula while collecting SSHD service diagnostic info in the NET module.",
    "BINx64/Pstat.exe": "WDK process/thread status utility; path constructed and referenced in TSS's core status-collection logic.",
    "BINx64/RecorderCommandLine.exe": "Command-line component of Windows Problem Steps Recorder (PSR) used for the 'Video' screen-recording data collection option named in TSS's synopsis; TSS checks for a running 'recordercommandline' process to manage recording state.",
    "BINx64/RecorderDll.dll": "No direct script reference found; name and bundling alongside RecorderCommandLine.exe/SdkDll.dll suggest it is a supporting library for the Problem Steps Recorder component, not independently confirmed.",
    "BINx64/SdkDll.dll": "No direct script reference found; name suggests an SDK support library, plausibly for RecorderCommandLine.exe, not independently confirmed.",
    "BINx64/cscdbdump.exe": "Offline Files (CSC) client-side cache database dump tool; invoked to dump the CSC database as part of client-component diagnostics on client SKUs.",
    "BINx64/ctsTraffic.exe": "Likely Microsoft's open-source CTS-Traffic network stress/reliability testing tool, bundled by name convention alongside other network performance tools (NTttcp, latte); no direct script invocation was found in the reviewed scripts.",
    "BINx64/dfsutil.exe": "Distributed File System (DFS) utility; invoked with /PKTflush to flush the DFS referral cache as part of DFS diagnostics.",
    "BINx64/dpmcmd.exe": "Data Protection Manager (DPM) command-line tool; invoked with 'qe all-procs-v' to enumerate DPM process queue state as part of DPM diagnostics in the NET module.",
    "BINx64/du.exe": "Likely Sysinternals Du (disk usage) by name and Sysinternals-suite bundling convention, but the automated script matches were false positives (matched unrelated changelog/URL text containing the substring 'du') — no confirmed direct invocation found.",
    "BINx64/evparse.exe": "Event log parser utility ('EvParse') — invoked via a companion DC_EvParser.ps1 script to parse storage-related System log events into an HTML report.",
    "BINx64/fcinfo.exe": "Fibre Channel Information utility (from the WDK) — invoked via a companion DC_FCInfo.ps1 script to collect Fibre Channel HBA/adapter information.",
    "BINx64/hbaapi.dll": "Fibre Channel HBA API library, a runtime dependency of fcinfo.exe; referenced/renamed per-architecture by the FCInfo collection script.",
    "BINx64/hbatapi.dll": "Fibre Channel HBA test/trace API library, bundled alongside hbaapi.dll as a dependency of fcinfo.exe.",
    "BINx64/kdbgctrl.exe": "Kernel debugger control utility — used to query/resize the page file based on dump-type configuration ahead of kernel dump collection.",
    "BINx64/latte.exe": "Microsoft Latte — low-latency network round-trip benchmarking tool; invoked with a constructed target address/port as part of network performance test scenarios.",
    "BINx64/notmyfaultc.exe": "Sysinternals NotMyFault (console build) — deliberately induces a crash, hang, or leak for testing crash-dump collection; TSS checks for its presence via Get-Command before offering it as a test-fault trigger.",
    "BINx64/poolmon.exe": "Windows kernel pool memory usage monitor (see BIN/poolmon.exe); x64 build, gated by the same -PoolMon/-noPoolMon controls.",
    "BINx64/tmq.exe": "No confirmed direct script reference (the one substring match found was inside an unrelated base64-encoded certificate blob, a false positive); by naming convention alongside tmqsite/tmqstate/tmqstore/tmqtry, likely part of an MSMQ (Microsoft Message Queuing) diagnostic/test toolset.",
    "BINx64/tmqsite.dll": "No direct script reference found; by naming convention, likely a supporting library for the tmq.exe MSMQ diagnostic toolset.",
    "BINx64/tmqstate.dll": "Referenced when building an output filename for 'tmqstate' diagnostic data in the INT (integration/messaging) module — consistent with an MSMQ state-inspection component.",
    "BINx64/tmqstore.dll": "No direct script reference found; by naming convention, likely a supporting library for the tmq.exe MSMQ diagnostic toolset (message store component).",
    "BINx64/tmqtry.dll": "No direct script reference found; by naming convention, likely a supporting library for the tmq.exe MSMQ diagnostic toolset (connectivity-try component).",
    "BINx64/vshadow.exe": "Microsoft VShadow (VSS test/requestor tool from the WDK) — invoked with -wm2 to dump Volume Shadow Copy metadata writer information.",
    "BINx64/vssagent.exe": "No direct script reference found; by naming convention, a Volume Shadow Copy Service (VSS) agent/writer test component bundled alongside vshadow.exe and vsstrace.exe.",
    "BINx64/vsstrace.exe": "Volume Shadow Copy Service (VSS) tracing tool; its associated ETW trace provider GUID (VSSTraceLogProvider) is registered in the storage (SHA) module.",
    "BINx64/xbootmgr.exe": "Windows boot/shutdown performance tracing tool (predecessor to WPR's boot-trace functionality); no direct script reference was found, consistent with it being a legacy/optional tool retained for older-OS compatibility.",
    "BINx86/Checksym.exe": "32-bit build of the file-version enumeration tool (see BINx64/Checksym.exe).",
    "BINx86/NTttcp.exe": "32-bit build of the NTttcp network throughput benchmarking tool (see BINx64/NTttcp.exe).",
    "BINx86/PsGetsid.exe": "32-bit build of Sysinternals PsGetSid (see BINx64/PsGetsid.exe).",
    "BINx86/Pstat.exe": "32-bit build of the WDK process/thread status utility (see BINx64/Pstat.exe).",
    "BINx86/RecorderCommandLine.exe": "32-bit build of the Problem Steps Recorder command-line component (see BINx64/RecorderCommandLine.exe).",
    "BINx86/RecorderDll.dll": "32-bit build of the Recorder support library (see BINx64/RecorderDll.dll); not independently confirmed.",
    "BINx86/SdkDll.dll": "32-bit build of the SDK support library (see BINx64/SdkDll.dll); not independently confirmed.",
    "BINx86/cscdbdump.exe": "32-bit build of the Offline Files cache database dump tool (see BINx64/cscdbdump.exe).",
    "BINx86/dfsutil.exe": "32-bit build of the DFS utility (see BINx64/dfsutil.exe).",
    "BINx86/dpmcmd.exe": "32-bit build of the Data Protection Manager command-line tool (see BINx64/dpmcmd.exe).",
    "BINx86/du.exe": "32-bit build corresponding to BINx64/du.exe; same caveat applies — no confirmed direct invocation found (automated matches were false positives).",
    "BINx86/evparse.exe": "32-bit build of the event log parser utility (see BINx64/evparse.exe).",
    "BINx86/fcinfo.exe": "32-bit build of the Fibre Channel Information utility (see BINx64/fcinfo.exe).",
    "BINx86/hbaapi.dll": "32-bit build of the Fibre Channel HBA API library (see BINx64/hbaapi.dll).",
    "BINx86/hbatapi.dll": "32-bit build of the Fibre Channel HBA test/trace API library (see BINx64/hbatapi.dll).",
    "BINx86/notmyfaultc.exe": "32-bit build of Sysinternals NotMyFault console (see BINx64/notmyfaultc.exe).",
    "BINx86/vshadow.exe": "32-bit build of the VShadow VSS test tool (see BINx64/vshadow.exe).",
    "BINx86/vssagent.exe": "32-bit build corresponding to BINx64/vssagent.exe; not independently confirmed.",
    "BINx86/vsstrace.exe": "32-bit build of the VSS tracing tool (see BINx64/vsstrace.exe).",
    "config/GUI/tssGUI-icons.dll": "Resource-only icon library for the TSSGUI front-end; loaded exclusively via Shell32!ExtractIconEx (no code execution) — see the detailed weak-link analysis in section 3.3.2 of the report.",
    "psSDP/Diag/global/DiagPackage.dll": "Windows Diagnostic Package framework component; the psSDP diagnostic scripts test for a companion .diagpkg manifest file consistent with this framework.",
    "psSDP/Diag/global/DumpEVT.exe": "Event log dump utility ('DumpEVT') — invoked to export Windows Event Log contents to files as part of psSDP diagnostic data collection (e.g. DPM event logs).",
    "psSDP/Diag/global/MGADiag.exe": "Windows/Office Genuine Advantage diagnostic tool — invoked to produce a WGADiag.txt licensing-validation diagnostic report.",
    "psSDP/Diag/global/SAN.exe": "No confirmed direct script reference (the automated match was a false positive on an unrelated GUI/Copilot function name); purpose not independently confirmed from the reviewed scripts, though the name suggests a Storage Area Network diagnostic tool consistent with the surrounding psSDP/Diag/global storage tools.",
    "psSDP/Diag/global/Showpriv.exe": "Duplicate copy of the privilege-enumeration tool bundled specifically for the psSDP diagnostic framework (see BIN/Showpriv.exe); invoked identically via the user-rights diagnostic script.",
    "psSDP/Diag/global/WSRUNAMD64.EXE": "No direct script reference found; by naming convention, an architecture-specific (AMD64) launcher/runtime component for the psSDP diagnostic framework, not independently confirmed.",
    "psSDP/Diag/global/WSRUNI386.EXE": "No direct script reference found; 32-bit (i386) counterpart to WSRUNAMD64.EXE, not independently confirmed.",
    "psSDP/Diag/global/autorunsc.exe": "Duplicate copy of Sysinternals Autoruns bundled for the psSDP diagnostic framework (see BIN/autorunsc.exe); invoked by the same registry-autoruns check script.",
    "psSDP/Diag/global/cdb.exe": "Microsoft Console Debugger (cdb.exe, from Debugging Tools for Windows) — referenced in obfuscated/encoded blocks of TSSGUI.ps1 and xray.ps1 that could not be reliably attributed to a specific invocation in this review; bundled as a standard user-mode debugger for the diagnostic framework.",
    "psSDP/Diag/global/certadm.dll": "Certificate Services administration library — no direct script reference found, plausibly used by ADCS (certificate authority) -related diagnostic scripts elsewhere in the toolkit, not independently confirmed.",
    "psSDP/Diag/global/clusmps.exe": "Cluster diagnostic tool — invoked with /S /G /P: flags to collect Windows Failover Cluster minimal poll-set information.",
    "psSDP/Diag/global/dbgeng.dll": "Debug engine library (from Debugging Tools for Windows) — a runtime dependency of cdb.exe; no direct script reference found beyond its bundling alongside the debugger.",
    "psSDP/Diag/global/dbghelp.dll": "Debug help library — used directly via P/Invoke (MiniDumpWriteDump) from TSS.ps1 and a dedicated AD performance data collection script to produce process memory dumps.",
    "psSDP/Diag/global/devcon.exe": "Duplicate copy of the Device Console tool bundled for the psSDP diagnostic framework (see BIN/devcon.exe); invoked by the same device/connection diagnostic script.",
    "psSDP/Diag/global/dosdev.exe": "WDK tool that creates/enumerates MS-DOS device name symbolic links; invoked by a dedicated DC_DOSDev.ps1 diagnostic script.",
    "psSDP/Diag/global/fltrfind.exe": "WDK filter-manager utility — lists upper/lower filter drivers attached to volumes; invoked by a dedicated DC_Fltrfind.ps1 diagnostic script.",
    "psSDP/Diag/global/memsnap.exe": "Kernel pool memory usage snapshot tool; output redirected to a memsnap.txt file as part of process-info diagnostic collection.",
    "psSDP/Diag/global/vshadow-x64.exe": "x64 build of the VShadow VSS test tool bundled for the psSDP diagnostic framework (see BINx64/vshadow.exe); no direct script reference found beyond its bundling.",
    "psSDP/Diag/global/vshadow.exe": "Duplicate copy of the VShadow VSS test tool bundled for the psSDP diagnostic framework (see BIN.../vshadow.exe); invoked identically via the system-info diagnostic script.",
    "scripts/CRUtil/CRUtil.exe": "Credential Roaming diagnostic/repair utility ('CRUtil') — moved into TSS from a standalone tool per its module changelog; used by the accompanying CRU.ps1 wrapper script for AD credential-roaming diagnostics.",
    "scripts/CRUtil/CredRoamADUserCmdLet.dll": "PowerShell cmdlet library for AD-based credential roaming data collection, loaded conditionally by CRU.ps1 based on OS architecture.",
    "scripts/CRUtil/CredRoamADUserCmdLetAMD64.dll": "AMD64 build of the AD credential-roaming cmdlet library, loaded conditionally by CRU.ps1 on 64-bit systems.",
    "scripts/CRUtil/CredRoamLVRCmdLet.dll": "PowerShell cmdlet library for Live ID/LVR-based credential roaming data collection, loaded conditionally by CRU.ps1.",
    "scripts/CRUtil/CredRoamLVRCmdLetAMD64.dll": "AMD64 build of the LVR credential-roaming cmdlet library, loaded conditionally by CRU.ps1 on 64-bit systems.",
    "scripts/CRUtil/CredRoamLocalUserData.dll": "Local-user credential-roaming data cmdlet, installed via install_cru.ps1 and queried via a dedicated get_complete_user_credroam_data.ps1 helper script.",
    "scripts/WinPE/Procmon24.SYS": "Kernel-mode driver component of Process Monitor 24 (WinPE-specific build); TSS grants registry read/permission-read ACLs on its service instance key as part of setup.",
}
